### ISSUE TITLE
Unfork

### ISSUE THREAD

**Issue by sandstrom** [julik/zip_kit#13]
This is a great project! 🏅 

To make it more obvious that this is the canonical repository, I'd suggest unforking from the original repo (removing the text "forked from …"). 

To unfork, simply contact Github support and explain that the other repo is stale/old and that you want to unfork. They'll fix it within ~1 day.

Having a non-forked repo will help signal that this is the canonical repo, which helps focusing PRs and issues to this repo. 

Perhaps we can also ask the old repo to add a link to this repo in their readme?

**Comment by julik** [comment]
Good idea. I don't know re. the old repo - the repo management at WT has become very structured and I already had to poke a few folks to make the fork possible. But de-forking the repo here is something I can certainly do.

Thank you for the kind words.

**Comment by julik** [comment]
What I saw is that Github currently suggests to delete the repo and re-push it at the same URL, recreating it. That will lose the few issues and PRs that are already in the repo. I navigated the support portal for a while trying to figure out how to place a support request for unforking. Time for dealing with bureacracies is somewhat limited, so I will put this on a backburner for now 🙏

**Comment by sandstrom** [comment]
@julik If you are paying for Github in any way, I think this is the link: https://support.github.com/

<img width="750" alt="image" src="https://github.com/user-attachments/assets/87d3b1bd-9e2e-41d1-a2c4-31943ca3d481">

If not, I don't think it's possible to get hold of their support team unfortunately. 

I can try asking them if you want to, but they'd probably want your confirmation as an account owner.

Maybe if you make a clear statement about your wish to unfork in this chat thread, and I'll link to this issue.

**Comment by julik** [comment]
It's done! ✈️
