### ISSUE TITLE
`ZipKit::PathSet::Conflict` When trying to follow example

### ISSUE THREAD

**Issue by salmonsteakk** [julik/zip_kit#15]
Hey there, I'm trying to use zip kit to upload my zip file as I am compressing it. Essentially it seems like what [this](https://github.com/julik/zip_kit?tab=readme-ov-file#writing-into-streaming-destinations) example is doing. But, I'm getting a `ZipKit::PathSet::Conflict` error as shown:

<img width="458" alt="image" src="https://github.com/user-attachments/assets/abb45cca-ed0d-40d7-baf8-4933ff065d8f">

Does anyone have any insights to this? For reference, I'm also using `aws-sdk-s3` gem, version 1.119.2. My endpoint is a cloudflare R2 bucket which has the [AWS S3 API compatibility](https://developers.cloudflare.com/r2/api/s3/api/). I've also tried updated my `aws-sdk-s3` gem to the latest version and I have no luck.

Any help would be appreciated!

**Comment by salmonsteakk** [comment]
I found out why, I had to use `binmode` for `write_stream`:

```ruby
 obj.upload_stream do |write_stream|
      write_stream.binmode
...
```

**Comment by julik** [comment]
I'll add this to the examples, thanks!

**Comment by julik** [comment]
@salmonsteak1 I think you bumped into the same issue as the one in #19 I will investigate as it's not nice at all
